spring.application.name=galacticShelter

#Tomcat configuration
server.port=9000

#Log level configuration
logging.level.root=ERROR
logging.level.com.galactic.shelter=INFO
#logging.level.org.springframework=DEBUG
logging.level.org.springframework.boot.autoconfigure.h2=DEBUG
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter=DEBUG

#H2 Configuration
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization: true
spring.sql.init.mode=always
spring.profiles.active=dev
spring.sql.init.schema-locations=classpath:/db/schema.sql